// eslint-disable-next-line no-undef
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,css,scss}'],
  theme: {
    extend: {
      colors: {
        'surface-container': '#eceef0',
        'surface-variant': '#e0e3e5',
        'on-tertiary-fixed': '#00201c',
        'on-error-container': '#93000a',
        'on-secondary-container': '#57657a',
        'error-container': '#ffdad6',
        'surface-container-low': '#f2f4f6',
        'on-primary': '#ffffff',
        'surface-bright': '#f7f9fb',
        'on-primary-container': '#87a4cf',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        secondary: '#515f74',
        'secondary-container': '#d5e3fc',
        'on-secondary-fixed': '#0d1c2e',
        surface: '#f7f9fb',
        'surface-tint': '#426087',
        'on-surface': '#191c1e',
        'surface-container-highest': '#e0e3e5',
        'secondary-fixed-dim': '#b9c7df',
        'on-surface-variant': '#43474e',
        'inverse-primary': '#abc8f5',
        'tertiary-container': '#004139',
        'inverse-surface': '#2d3133',
        'surface-dim': '#d8dadc',
        tertiary: '#002924',
        'on-tertiary-container': '#00b7a4',
        'tertiary-fixed-dim': '#3cddc7',
        'on-background': '#191c1e',
        'primary-container': '#1a3a5f',
        'on-tertiary-fixed-variant': '#005047',
        error: '#ba1a1a',
        'primary-fixed-dim': '#abc8f5',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        primary: '#002446',
        'inverse-on-surface': '#eff1f3',
        'outline-variant': '#c3c6cf',
        'secondary-fixed': '#d5e3fc',
        'primary-fixed': '#d3e3ff',
        'on-secondary-fixed-variant': '#3a485b',
        'surface-container-lowest': '#ffffff',
        background: '#f7f9fb',
        'on-primary-fixed': '#001c39',
        outline: '#73777f',
        'tertiary-fixed': '#62fae3',
        'on-primary-fixed-variant': '#2a486e',
        yellow: '#efc603',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      keyframes: {
        typing: {
          '0%, 100%': {width: '0%'},
          '30%, 70%': {width: '100%'},
        },
        blink: {
          '0%': {
            opacity: 0,
          },
        },
        'rotate-loader': {
          '0%': {
            transform: 'rotate(0deg)',
            strokeDashoffset: '360%',
          },
          '100%': {
            transform: 'rotate(360deg)',
            strokeDashoffset: '-360%',
          },
        },
      },
      screens: {
        touch: {raw: 'only screen and (pointer: coarse)'},
      },
    },
  },
  // eslint-disable-next-line no-undef
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
};
